language: node_js
node_js:
  - "10"
  - "12"
  - "14"
services: mongodb  
cache:  
  directories:
    - "node_modules"
deploy:
  - provider: script
    skip_cleanup: true
    script: chmod +x ./deploy.sh && ./deploy.sh
    on:
      branch: master